// src/webview/shader/scripts/codegen/babylon.ts
import type { ShaderDefinition } from "../../../../scene/shader/types";
import { CHANNEL_ORDER } from "../../../../scene/shader/defaults";
import { getChannelUsage, colorToVec4Literal } from "./common";
import { generateGLSL } from "./glsl";

export function generateBabylon(shader: ShaderDefinition): string {
	const { vertex, fragment } = generateGLSL(shader);

	const lines: string[] = [];
	lines.push(`// ─────────────────────────────────────────────`);
	lines.push(`// ${shader.name} — Babylon.js ShaderMaterial`);
	lines.push(`// Generated by Weaver Shader Editor`);
	lines.push(`// ─────────────────────────────────────────────`);
	lines.push(``);
	lines.push(`import { ShaderMaterial, Effect, Vector3, Vector4, Texture, Color3 } from "@babylonjs/core";`);
	lines.push(``);
	lines.push(`export const ${toVarName(shader.name)}VertexShader = \``);
	lines.push(escapeTemplate(vertex));
	lines.push(`\`;`);
	lines.push(``);
	lines.push(`export const ${toVarName(shader.name)}FragmentShader = \``);
	lines.push(escapeTemplate(fragment));
	lines.push(`\`;`);
	lines.push(``);

	lines.push(`export function create${toPascalCase(shader.name)}Material(scene) {`);
	lines.push(`    Effect.ShadersStore["${shader.name}VertexShader"] = ${toVarName(shader.name)}VertexShader;`);
	lines.push(`    Effect.ShadersStore["${shader.name}FragmentShader"] = ${toVarName(shader.name)}FragmentShader;`);
	lines.push(``);
	lines.push(`    const material = new ShaderMaterial("${shader.name}", scene, {`);
	lines.push(`        vertex: "${shader.name}",`);
	lines.push(`        fragment: "${shader.name}",`);
	lines.push(`    }, {`);
	lines.push(`        attributes: ["position", "normal", "uv"],`);
	lines.push(`        uniforms: ["world", "worldView", "worldViewProjection", "view", "projection", "uCameraPos", "uLightDir", "uLightColor", "uLightIntensity", ${collectUniformNames(shader)}],`);
	lines.push(`    });`);
	lines.push(``);

	// defaults
	lines.push(`    // ─── defaults ───`);
	for (const key of CHANNEL_ORDER) {
		const ch = shader.channels[key];
		if (!ch.enabled) continue;
		const u = getChannelUsage(ch);

		if (u.usesColor) {
			const c = ch.color ?? [0.5, 0.5, 0.5, 1];
			lines.push(`    material.setVector4("u_${key}_color", new Vector4(${c[0].toFixed(3)}, ${c[1].toFixed(3)}, ${c[2].toFixed(3)}, ${c[3].toFixed(3)}));`);
		}
		if (u.usesNumber) {
			lines.push(`    material.setFloat("u_${key}_number", ${(ch.number ?? 0).toFixed(4)});`);
		}
		if (u.usesIntensity) {
			lines.push(`    material.setFloat("u_${key}_intensity", ${(ch.intensity ?? 1).toFixed(4)});`);
		}
		if (u.usesTexture) {
			lines.push(`    material.setInt("u_${key}_hasTexture", 0);`);
		}
	}
	lines.push(``);
	lines.push(`    material.setVector3("uCameraPos", scene.activeCamera?.position ?? Vector3.Zero());`);
	lines.push(`    material.setVector3("uLightDir", new Vector3(-0.5, -1, -0.3));`);
	lines.push(`    material.setColor3("uLightColor", new Color3(1, 1, 1));`);
	lines.push(`    material.setFloat("uLightIntensity", 1.2);`);
	lines.push(``);
	lines.push(`    return material;`);
	lines.push(`}`);
	lines.push(``);

	// usage
	lines.push(`// ─── Usage ───`);
	lines.push(`// const material = create${toPascalCase(shader.name)}Material(scene);`);
	lines.push(`// mesh.material = material;`);

	return lines.join("\n");
}

function toVarName(name: string): string {
	return name.replace(/[^a-zA-Z0-9]/g, "_").replace(/^(\d)/, "_$1");
}

function toPascalCase(name: string): string {
	return name.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^(.)/, (c) => c.toUpperCase());
}

function collectUniformNames(shader: ShaderDefinition): string {
	const names: string[] = [];
	for (const key of CHANNEL_ORDER) {
		const ch = shader.channels[key];
		if (!ch.enabled) continue;
		const u = getChannelUsage(ch);
		if (u.usesColor) names.push(`"u_${key}_color"`);
		if (u.usesNumber) names.push(`"u_${key}_number"`);
		if (u.usesTexture) names.push(`"u_${key}_hasTexture"`);
		if (u.usesIntensity) names.push(`"u_${key}_intensity"`);
	}
	return names.join(", ");
}

function escapeTemplate(s: string): string {
	return s.replace(/`/g, "\\`").replace(/\$/g, "\\$");
}
