// src/webview/shader/scripts/codegen/glsl.ts
import type { ShaderDefinition } from "../../../../scene/shader/types";
import { CHANNEL_ORDER } from "../../../../scene/shader/defaults";
import { getChannelUsage, colorToVec4Literal } from "./common";

export function generateGLSL(shader: ShaderDefinition): { vertex: string; fragment: string } {
	return {
		vertex: generateGLSLVertex(shader),
		fragment: generateGLSLFragment(shader),
	};
}

function generateGLSLVertex(shader: ShaderDefinition): string {
	const lines: string[] = [];
	lines.push(`// ─────────────────────────────────────────────`);
	lines.push(`// ${shader.name} — Vertex Shader (GLSL 100)`);
	lines.push(`// Generated by Weaver Shader Editor`);
	lines.push(`// ─────────────────────────────────────────────`);
	lines.push(``);

	lines.push(`#version 100`);
	lines.push(``);
	lines.push(`precision highp float;`);
	lines.push(``);
	lines.push(`attribute vec3 aPosition;`);
	lines.push(`attribute vec3 aNormal;`);
	lines.push(`attribute vec2 aUV;`);
	lines.push(``);
	lines.push(`uniform mat4 uProjection;`);
	lines.push(`uniform mat4 uView;`);
	lines.push(`uniform mat4 uModel;`);
	lines.push(`uniform mat3 uNormalMatrix;`);
	lines.push(``);
	lines.push(`varying vec3 vWorldPos;`);
	lines.push(`varying vec3 vNormal;`);
	lines.push(`varying vec2 vUV;`);
	lines.push(``);
	lines.push(`void ${shader.output.entryName}() {`);
	lines.push(`    vec4 worldPos = uModel * vec4(aPosition, 1.0);`);
	lines.push(`    vWorldPos = worldPos.xyz;`);
	lines.push(`    vNormal = normalize(uNormalMatrix * aNormal);`);
	lines.push(`    vUV = aUV;`);
	lines.push(`    gl_Position = uProjection * uView * worldPos;`);
	lines.push(`}`);

	return lines.join("\n");
}

function generateGLSLFragment(shader: ShaderDefinition): string {
	const lines: string[] = [];
	lines.push(`// ─────────────────────────────────────────────`);
	lines.push(`// ${shader.name} — Fragment Shader (GLSL 100)`);
	lines.push(`// Generated by Weaver Shader Editor`);
	lines.push(`// ─────────────────────────────────────────────`);
	lines.push(``);
	lines.push(`#version 100`);
	lines.push(``);
	lines.push(`precision highp float;`);
	lines.push(``);

	// varyings
	lines.push(`varying vec3 vWorldPos;`);
	lines.push(`varying vec3 vNormal;`);
	lines.push(`varying vec2 vUV;`);
	lines.push(``);

	// camera + light
	lines.push(`uniform vec3 uCameraPos;`);
	lines.push(`uniform vec3 uLightDir;`);
	lines.push(`uniform vec3 uLightColor;`);
	lines.push(`uniform float uLightIntensity;`);
	lines.push(``);

	// channel uniforms
	for (const key of CHANNEL_ORDER) {
		const ch = shader.channels[key];
		if (!ch.enabled) continue;

		const u = getChannelUsage(ch);
		const header = `// ${key}`;

		if (u.usesColor) lines.push(`${header}\nuniform vec4 u_${key}_color;`);
		if (u.usesNumber) lines.push(`uniform float u_${key}_number;`);
		if (u.usesTexture) {
			lines.push(`uniform sampler2D u_${key}_texture;`);
			lines.push(`uniform bool u_${key}_hasTexture;`);
		}
		if (u.usesIntensity) lines.push(`uniform float u_${key}_intensity;`);
		lines.push(``);
	}

	// helper
	lines.push(`vec4 sampleTex(sampler2D tex, bool has, vec4 fallback) {`);
	lines.push(`    if (!has) return fallback;`);
	lines.push(`    return texture2D(tex, vUV);`);
	lines.push(`}`);
	lines.push(``);

	// main
	lines.push(`void main() {`);
	lines.push(`    vec3 N = normalize(vNormal);`);
	lines.push(`    vec3 V = normalize(uCameraPos - vWorldPos);`);
	lines.push(`    vec3 L = normalize(-uLightDir);`);
	lines.push(``);

	// base color
	const bc = shader.channels.baseColor;
	if (bc.enabled && bc.source === "color") {
		lines.push(`    vec4 baseColor = u_baseColor_color;`);
	} else if (bc.enabled && bc.source === "texture") {
		lines.push(`    vec4 baseColor = sampleTex(u_baseColor_texture, u_baseColor_hasTexture, vec4(1.0));`);
	} else if (bc.enabled && bc.source === "color-texture") {
		lines.push(`    vec4 baseColor = u_baseColor_color * sampleTex(u_baseColor_texture, u_baseColor_hasTexture, vec4(1.0)) * u_baseColor_intensity;`);
	} else {
		lines.push(`    vec4 baseColor = vec4(1.0);`);
	}
	lines.push(``);

	// roughness
	const rg = shader.channels.roughness;
	if (rg.enabled && rg.source === "number") {
		lines.push(`    float roughness = u_roughness_number;`);
	} else if (rg.enabled && rg.source === "texture") {
		lines.push(`    float roughness = sampleTex(u_roughness_texture, u_roughness_hasTexture, vec4(0.5)).r;`);
	} else if (rg.enabled && rg.source === "number-texture") {
		lines.push(`    float roughness = u_roughness_number * sampleTex(u_roughness_texture, u_roughness_hasTexture, vec4(1.0)).r * u_roughness_intensity;`);
	} else {
		lines.push(`    float roughness = 0.5;`);
	}

	// metallic
	const mt = shader.channels.metallic;
	if (mt.enabled && mt.source === "number") {
		lines.push(`    float metallic = u_metallic_number;`);
	} else if (mt.enabled && mt.source === "texture") {
		lines.push(`    float metallic = sampleTex(u_metallic_texture, u_metallic_hasTexture, vec4(0.0)).r;`);
	} else if (mt.enabled && mt.source === "number-texture") {
		lines.push(`    float metallic = u_metallic_number * sampleTex(u_metallic_texture, u_metallic_hasTexture, vec4(1.0)).r * u_metallic_intensity;`);
	} else {
		lines.push(`    float metallic = 0.0;`);
	}

	// emissive
	const em = shader.channels.emissive;
	if (em.enabled && em.source === "color") {
		lines.push(`    vec3 emissive = u_emissive_color.rgb * u_emissive_color.a;`);
	} else if (em.enabled && em.source === "texture") {
		lines.push(`    vec3 emissive = sampleTex(u_emissive_texture, u_emissive_hasTexture, vec4(0.0)).rgb;`);
	} else if (em.enabled && em.source === "color-texture") {
		lines.push(`    vec3 emissive = u_emissive_color.rgb * sampleTex(u_emissive_texture, u_emissive_hasTexture, vec4(1.0)).rgb * u_emissive_intensity;`);
	} else {
		lines.push(`    vec3 emissive = vec3(0.0);`);
	}

	// ao
	const ao = shader.channels.ao;
	if (ao.enabled && ao.source === "texture") {
		lines.push(`    float ao = sampleTex(u_ao_texture, u_ao_hasTexture, vec4(1.0)).r;`);
	} else {
		lines.push(`    float ao = 1.0;`);
	}

	// opacity
	const op = shader.channels.opacity;
	if (op.enabled && op.source === "number") {
		lines.push(`    float opacity = u_opacity_number;`);
	} else if (op.enabled && op.source === "texture") {
		lines.push(`    float opacity = sampleTex(u_opacity_texture, u_opacity_hasTexture, vec4(1.0)).a;`);
	} else if (op.enabled && op.source === "number-texture") {
		lines.push(`    float opacity = u_opacity_number * sampleTex(u_opacity_texture, u_opacity_hasTexture, vec4(1.0)).a * u_opacity_intensity;`);
	} else {
		lines.push(`    float opacity = 1.0;`);
	}
	lines.push(``);

	// lighting
	const lighting = shader.render.lighting;
	if (lighting === "unlit") {
		lines.push(`    vec3 finalColor = baseColor.rgb * ao + emissive;`);
	} else if (lighting === "lit") {
		lines.push(`    float NdotL = max(dot(N, L), 0.0);`);
		lines.push(`    vec3 diffuse = baseColor.rgb * NdotL * uLightColor * uLightIntensity * ao;`);
		lines.push(`    vec3 H = normalize(L + V);`);
		lines.push(`    float NdotH = max(dot(N, H), 0.0);`);
		lines.push(`    float shininess = mix(8.0, 256.0, 1.0 - roughness);`);
		lines.push(`    float spec = pow(NdotH, shininess);`);
		lines.push(`    vec3 ambient = baseColor.rgb * 0.15 * ao;`);
		lines.push(`    vec3 finalColor = ambient + diffuse + spec * uLightColor + emissive;`);
	} else {
		// pbr
		lines.push(`    float NdotL = max(dot(N, L), 0.0);`);
		lines.push(`    float NdotV = max(dot(N, V), 0.001);`);
		lines.push(`    vec3 F0 = mix(vec3(0.04), baseColor.rgb, metallic);`);
		lines.push(`    vec3 H = normalize(L + V);`);
		lines.push(`    float NdotH = max(dot(N, H), 0.0);`);
		lines.push(`    float VdotH = max(dot(V, H), 0.0);`);
		lines.push(`    vec3 F = F0 + (1.0 - F0) * pow(1.0 - VdotH, 5.0);`);
		lines.push(`    float alpha = roughness * roughness;`);
		lines.push(`    float k = alpha / 2.0;`);
		lines.push(`    float G1L = NdotL / (NdotL * (1.0 - k) + k);`);
		lines.push(`    float G1V = NdotV / (NdotV * (1.0 - k) + k);`);
		lines.push(`    float G = G1L * G1V;`);
		lines.push(`    float alpha2 = alpha * alpha;`);
		lines.push(`    float denom = NdotH * NdotH * (alpha2 - 1.0) + 1.0;`);
		lines.push(`    float D = alpha2 / (3.14159265 * denom * denom);`);
		lines.push(`    vec3 specularBRDF = (F * G * D) / max(4.0 * NdotL * NdotV, 0.001);`);
		lines.push(`    vec3 kD = (1.0 - F) * (1.0 - metallic);`);
		lines.push(`    vec3 diffuse = kD * baseColor.rgb / 3.14159265;`);
		lines.push(`    vec3 lighting = (diffuse + specularBRDF) * uLightColor * uLightIntensity * NdotL;`);
		lines.push(`    vec3 ambient = baseColor.rgb * 0.1 * ao;`);
		lines.push(`    vec3 finalColor = ambient + lighting * ao + emissive;`);
	}
	lines.push(``);

	// output
	const alphaMode = shader.render.alphaMode;
	if (alphaMode === "blend") {
		lines.push(`    gl_FragColor = vec4(finalColor, baseColor.a * opacity);`);
	} else if (alphaMode === "cutout") {
		lines.push(`    if (baseColor.a * opacity < 0.5) discard;`);
		lines.push(`    gl_FragColor = vec4(finalColor, 1.0);`);
	} else {
		lines.push(`    gl_FragColor = vec4(finalColor, 1.0);`);
	}

	lines.push(`}`);
	return lines.join("\n");
}
