// src/webview/shader/scripts/codegen/libgdx.ts
import type { ShaderDefinition } from "../../../../scene/shader/types";
import { CHANNEL_ORDER } from "../../../../scene/shader/defaults";
import { getChannelUsage } from "./common";

export function generateLibGDX(shader: ShaderDefinition): { vertex: string; fragment: string; java: string } {
	const vertex = generateLibGDXVertex(shader);
	const fragment = generateLibGDXFragment(shader);
	const java = generateLibGDXJava(shader);

	return { vertex, fragment, java };
}

function generateLibGDXVertex(shader: ShaderDefinition): string {
	const lines: string[] = [];
	lines.push(`// ${shader.name} — LibGDX Vertex Shader`);
	lines.push(`// Generated by Weaver Shader Editor`);
	lines.push(``);
	lines.push(`attribute vec3 a_position;`);
	lines.push(`attribute vec3 a_normal;`);
	lines.push(`attribute vec2 a_texCoord0;`);
	lines.push(``);
	lines.push(`uniform mat4 u_projTrans;`);
	lines.push(`uniform mat4 u_worldTrans;`);
	lines.push(`uniform mat3 u_normalMatrix;`);
	lines.push(``);
	lines.push(`varying vec3 v_worldPos;`);
	lines.push(`varying vec3 v_normal;`);
	lines.push(`varying vec2 v_texCoord0;`);
	lines.push(``);
	lines.push(`void ${shader.output.entryName}() {`);
	lines.push(`    vec4 worldPos = u_worldTrans * vec4(a_position, 1.0);`);
	lines.push(`    v_worldPos = worldPos.xyz;`);
	lines.push(`    v_normal = normalize(u_normalMatrix * a_normal);`);
	lines.push(`    v_texCoord0 = a_texCoord0;`);
	lines.push(`    gl_Position = u_projTrans * worldPos;`);
	lines.push(`}`);
	return lines.join("\n");
}

function generateLibGDXFragment(shader: ShaderDefinition): string {
	const lines: string[] = [];
	lines.push(`// ${shader.name} — LibGDX Fragment Shader`);
	lines.push(`// Generated by Weaver Shader Editor`);
	lines.push(``);
	lines.push(`#ifdef GL_ES`);
	lines.push(`precision mediump float;`);
	lines.push(`#endif`);
	lines.push(``);
	lines.push(`varying vec3 v_worldPos;`);
	lines.push(`varying vec3 v_normal;`);
	lines.push(`varying vec2 v_texCoord0;`);
	lines.push(``);
	lines.push(`uniform vec3 u_cameraPos;`);
	lines.push(`uniform vec3 u_lightDir;`);
	lines.push(`uniform vec3 u_lightColor;`);
	lines.push(`uniform float u_lightIntensity;`);
	lines.push(``);

	for (const key of CHANNEL_ORDER) {
		const ch = shader.channels[key];
		if (!ch.enabled) continue;
		const u = getChannelUsage(ch);
		if (u.usesColor) lines.push(`uniform vec4 u_${key}_color;`);
		if (u.usesNumber) lines.push(`uniform float u_${key}_number;`);
		if (u.usesTexture) lines.push(`uniform sampler2D u_${key}_texture;`);
		if (u.usesIntensity) lines.push(`uniform float u_${key}_intensity;`);
	}
	lines.push(``);
	lines.push(`void ${shader.output.entryName}() {`);

	// base color
	const bc = shader.channels.baseColor;
	if (bc.enabled && bc.source === "color") {
		lines.push(`    vec4 baseColor = u_baseColor_color;`);
	} else if (bc.enabled && bc.source === "texture") {
		lines.push(`    vec4 baseColor = texture2D(u_baseColor_texture, v_texCoord0);`);
	} else if (bc.enabled && bc.source === "color-texture") {
		lines.push(`    vec4 baseColor = u_baseColor_color * texture2D(u_baseColor_texture, v_texCoord0) * u_baseColor_intensity;`);
	} else {
		lines.push(`    vec4 baseColor = vec4(1.0);`);
	}

	// roughness
	const rg = shader.channels.roughness;
	if (rg.enabled && rg.source === "number") lines.push(`    float roughness = u_roughness_number;`);
	else if (rg.enabled && rg.source === "texture") lines.push(`    float roughness = texture2D(u_roughness_texture, v_texCoord0).r;`);
	else if (rg.enabled && rg.source === "number-texture") lines.push(`    float roughness = u_roughness_number * texture2D(u_roughness_texture, v_texCoord0).r * u_roughness_intensity;`);
	else lines.push(`    float roughness = 0.5;`);

	// metallic
	const mt = shader.channels.metallic;
	if (mt.enabled && mt.source === "number") lines.push(`    float metallic = u_metallic_number;`);
	else if (mt.enabled && mt.source === "texture") lines.push(`    float metallic = texture2D(u_metallic_texture, v_texCoord0).r;`);
	else if (mt.enabled && mt.source === "number-texture") lines.push(`    float metallic = u_metallic_number * texture2D(u_metallic_texture, v_texCoord0).r * u_metallic_intensity;`);
	else lines.push(`    float metallic = 0.0;`);

	lines.push(``);
	lines.push(`    vec3 N = normalize(v_normal);`);
	lines.push(`    vec3 V = normalize(u_cameraPos - v_worldPos);`);
	lines.push(`    vec3 L = normalize(-u_lightDir);`);
	lines.push(``);

	const lighting = shader.render.lighting;
	if (lighting === "unlit") {
		lines.push(`    vec3 finalColor = baseColor.rgb;`);
	} else if (lighting === "lit") {
		lines.push(`    float NdotL = max(dot(N, L), 0.0);`);
		lines.push(`    vec3 diffuse = baseColor.rgb * NdotL * u_lightColor * u_lightIntensity;`);
		lines.push(`    vec3 finalColor = diffuse;`);
	} else {
		lines.push(`    float NdotL = max(dot(N, L), 0.0);`);
		lines.push(`    float NdotV = max(dot(N, V), 0.001);`);
		lines.push(`    vec3 F0 = mix(vec3(0.04), baseColor.rgb, metallic);`);
		lines.push(`    vec3 H = normalize(L + V);`);
		lines.push(`    float NdotH = max(dot(N, H), 0.0);`);
		lines.push(`    vec3 F = F0 + (1.0 - F0) * pow(1.0 - max(dot(V, H), 0.0), 5.0);`);
		lines.push(`    float alpha = roughness * roughness;`);
		lines.push(`    float denom = NdotH * NdotH * (alpha * alpha - 1.0) + 1.0;`);
		lines.push(`    float D = (alpha * alpha) / (3.14159265 * denom * denom);`);
		lines.push(`    vec3 specular = (F * D) / max(4.0 * NdotL * NdotV, 0.001);`);
		lines.push(`    vec3 kD = (1.0 - F) * (1.0 - metallic);`);
		lines.push(`    vec3 lighting = (kD * baseColor.rgb / 3.14159265 + specular) * u_lightColor * u_lightIntensity * NdotL;`);
		lines.push(`    vec3 finalColor = lighting;`);
	}

	const alphaMode = shader.render.alphaMode;
	if (alphaMode === "blend") {
		lines.push(`    gl_FragColor = vec4(finalColor, baseColor.a);`);
	} else if (alphaMode === "cutout") {
		lines.push(`    if (baseColor.a < 0.5) discard;`);
		lines.push(`    gl_FragColor = vec4(finalColor, 1.0);`);
	} else {
		lines.push(`    gl_FragColor = vec4(finalColor, 1.0);`);
	}
	lines.push(`}`);
	return lines.join("\n");
}

function generateLibGDXJava(shader: ShaderDefinition): string {
	const lines: string[] = [];
	lines.push(`// ${shader.name} — LibGDX ShaderProgram`);
	lines.push(`// Generated by Weaver Shader Editor`);
	lines.push(``);
	lines.push(`import com.badlogic.gdx.graphics.glutils.ShaderProgram;`);
	lines.push(`import com.badlogic.gdx.graphics.Color;`);
	lines.push(`import com.badlogic.gdx.math.Vector3;`);
	lines.push(``);
	lines.push(`public class ${toPascalCase(shader.name)}Shader extends ShaderProgram {`);
	lines.push(``);
	lines.push(`    private static final String VERTEX =`);
	lines.push(`        "${"${'}"}vertex" +${"${'}"}"\\n" +`);
	lines.push(`        // ... (vertex source)`);
	lines.push(`        "";`);
	lines.push(``);
	lines.push(`    private static final String FRAGMENT =`);
	lines.push(`        // ... (fragment source)`);
	lines.push(`        "";`);
	lines.push(``);
	lines.push(`    public ${toPascalCase(shader.name)}Shader() {`);
	lines.push(`        super(VERTEX, FRAGMENT);`);
	lines.push(`    }`);
	lines.push(``);
	lines.push(`    public void setUniforms(Vector3 cameraPos, Vector3 lightDir) {`);
	lines.push(`        setUniformf("u_cameraPos", cameraPos);`);
	lines.push(`        setUniformf("u_lightDir", lightDir);`);
	lines.push(`        setUniformf("u_lightColor", 1f, 1f, 1f);`);
	lines.push(`        setUniformf("u_lightIntensity", 1.2f);`);

	for (const key of CHANNEL_ORDER) {
		const ch = shader.channels[key];
		if (!ch.enabled) continue;
		const u = getChannelUsage(ch);
		if (u.usesColor) {
			const c = ch.color ?? [0.5, 0.5, 0.5, 1];
			lines.push(`        setUniformf("u_${key}_color", ${c[0].toFixed(3)}f, ${c[1].toFixed(3)}f, ${c[2].toFixed(3)}f, ${c[3].toFixed(3)}f);`);
		}
		if (u.usesNumber) {
			lines.push(`        setUniformf("u_${key}_number", ${(ch.number ?? 0).toFixed(4)}f);`);
		}
		if (u.usesIntensity) {
			lines.push(`        setUniformf("u_${key}_intensity", ${(ch.intensity ?? 1).toFixed(4)}f);`);
		}
	}
	lines.push(`    }`);
	lines.push(`}`);
	return lines.join("\n");
}

function toPascalCase(name: string): string {
	return name.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^(.)/, (c) => c.toUpperCase());
}
