// src/webview/shader/scripts/codegen/monogame.ts
import type { ShaderDefinition } from "../../../../scene/shader/types";
import { CHANNEL_ORDER } from "../../../../scene/shader/defaults";
import { getChannelUsage } from "./common";

export function generateMonoGame(shader: ShaderDefinition): string {
	const lines: string[] = [];

	// ✅ collect texture samplers
	const textureSamplers: Array<{ key: string; path: string; sampler: string }> = [];
	let samplerIdx = 1;
	for (const key of CHANNEL_ORDER) {
		const ch = shader.channels[key];
		if (!ch.enabled) continue;
		const u = getChannelUsage(ch);
		if (u.usesTexture) {
			textureSamplers.push({ key, path: ch.texture ?? "(none)", sampler: `s${samplerIdx}` });
			samplerIdx++;
		}
	}

	lines.push(`// ─────────────────────────────────────────────`);
	lines.push(`// ${shader.name} — MonoGame / HLSL Effect`);
	lines.push(`// Generated by Weaver Shader Editor`);
	lines.push(`// ─────────────────────────────────────────────`);
	lines.push(``);

	// samplers
	lines.push(`sampler TextureSampler : register(s0);`);
	for (const t of textureSamplers) {
		lines.push(`// ${t.key} texture: ${t.path} → register(${t.sampler})`);
	}
	lines.push(``);

	// uniforms
	lines.push(`float4x4 World;`);
	lines.push(`float4x4 View;`);
	lines.push(`float4x4 Projection;`);
	lines.push(`float3x3 NormalMatrix;`);
	lines.push(`float3 CameraPos;`);
	lines.push(`float3 LightDir;`);
	lines.push(`float3 LightColor;`);
	lines.push(`float LightIntensity;`);
	lines.push(``);

	for (const key of CHANNEL_ORDER) {
		const ch = shader.channels[key];
		if (!ch.enabled) continue;
		const u = getChannelUsage(ch);
		if (u.usesColor) lines.push(`float4 u_${key}_color;`);
		if (u.usesNumber) lines.push(`float u_${key}_number;`);
		if (u.usesIntensity) lines.push(`float u_${key}_intensity;`);
	}
	lines.push(``);

	// structs
	lines.push(`struct VSInput {`);
	lines.push(`    float4 Position : POSITION0;`);
	lines.push(`    float3 Normal : NORMAL0;`);
	lines.push(`    float2 UV : TEXCOORD0;`);
	lines.push(`};`);
	lines.push(``);
	lines.push(`struct VSOutput {`);
	lines.push(`    float4 Position : SV_POSITION;`);
	lines.push(`    float3 WorldPos : TEXCOORD0;`);
	lines.push(`    float3 Normal : TEXCOORD1;`);
	lines.push(`    float2 UV : TEXCOORD2;`);
	lines.push(`};`);
	lines.push(``);

	// vertex
	lines.push(`VSOutput ${shader.output.entryName}_VS(VSInput input) {`);
	lines.push(`    VSOutput output;`);
	lines.push(`    float4 worldPos = mul(input.Position, World);`);
	lines.push(`    output.WorldPos = worldPos.xyz;`);
	lines.push(`    output.Position = mul(mul(worldPos, View), Projection);`);
	lines.push(`    output.Normal = normalize(mul(input.Normal, NormalMatrix));`);
	lines.push(`    output.UV = input.UV;`);
	lines.push(`    return output;`);
	lines.push(`}`);
	lines.push(``);

	// pixel
	lines.push(`float4 ${shader.output.entryName}_PS(VSOutput input) : SV_TARGET {`);
	lines.push(`    float3 N = normalize(input.Normal);`);
	lines.push(`    float3 V = normalize(CameraPos - input.WorldPos);`);
	lines.push(`    float3 L = normalize(-LightDir);`);
	lines.push(``);

	// base color
	const bc = shader.channels.baseColor;
	if (bc.enabled && bc.source === "color") {
		lines.push(`    float4 baseColor = u_baseColor_color;`);
	} else if (bc.enabled && bc.source === "texture") {
		lines.push(`    float4 baseColor = tex2D(TextureSampler, input.UV);`);
	} else if (bc.enabled && bc.source === "color-texture") {
		lines.push(`    float4 baseColor = u_baseColor_color * tex2D(TextureSampler, input.UV) * u_baseColor_intensity;`);
	} else {
		lines.push(`    float4 baseColor = float4(1, 1, 1, 1);`);
	}

	// roughness
	const rg = shader.channels.roughness;
	if (rg.enabled && rg.source === "number") lines.push(`    float roughness = u_roughness_number;`);
	else if (rg.enabled && rg.source === "number-texture") lines.push(`    float roughness = u_roughness_number * tex2D(TextureSampler, input.UV).r * u_roughness_intensity;`);
	else lines.push(`    float roughness = 0.5;`);

	// metallic
	const mt = shader.channels.metallic;
	if (mt.enabled && mt.source === "number") lines.push(`    float metallic = u_metallic_number;`);
	else if (mt.enabled && mt.source === "number-texture") lines.push(`    float metallic = u_metallic_number * tex2D(TextureSampler, input.UV).r * u_metallic_intensity;`);
	else lines.push(`    float metallic = 0.0;`);
	lines.push(``);

	const lighting = shader.render.lighting;
	if (lighting === "unlit") {
		lines.push(`    float3 finalColor = baseColor.rgb;`);
	} else if (lighting === "lit") {
		lines.push(`    float NdotL = max(dot(N, L), 0.0);`);
		lines.push(`    float3 finalColor = baseColor.rgb * NdotL * LightColor * LightIntensity;`);
	} else {
		lines.push(`    float NdotL = max(dot(N, L), 0.0);`);
		lines.push(`    float NdotV = max(dot(N, V), 0.001);`);
		lines.push(`    float3 F0 = lerp(float3(0.04, 0.04, 0.04), baseColor.rgb, metallic);`);
		lines.push(`    float3 H = normalize(L + V);`);
		lines.push(`    float NdotH = max(dot(N, H), 0.0);`);
		lines.push(`    float VdotH = max(dot(V, H), 0.0);`);
		lines.push(`    float3 F = F0 + (1.0 - F0) * pow(1.0 - VdotH, 5.0);`);
		lines.push(`    float alpha = roughness * roughness;`);
		lines.push(`    float denom = NdotH * NdotH * (alpha * alpha - 1.0) + 1.0;`);
		lines.push(`    float D = (alpha * alpha) / (3.14159265 * denom * denom);`);
		lines.push(`    float3 specular = (F * D) / max(4.0 * NdotL * NdotV, 0.001);`);
		lines.push(`    float3 kD = (1.0 - F) * (1.0 - metallic);`);
		lines.push(`    float3 lighting = (kD * baseColor.rgb / 3.14159265 + specular) * LightColor * LightIntensity * NdotL;`);
		lines.push(`    float3 finalColor = lighting;`);
	}
	lines.push(``);

	const alphaMode = shader.render.alphaMode;
	if (alphaMode === "blend") {
		lines.push(`    return float4(finalColor, baseColor.a);`);
	} else if (alphaMode === "cutout") {
		lines.push(`    clip(baseColor.a - 0.5);`);
		lines.push(`    return float4(finalColor, 1.0);`);
	} else {
		lines.push(`    return float4(finalColor, 1.0);`);
	}
	lines.push(`}`);
	lines.push(``);

	// technique
	lines.push(`technique Technique1 {`);
	lines.push(`    pass Pass1 {`);
	lines.push(`        VertexShader = compile vs_4_0_level_9_1 ${shader.output.entryName}_VS();`);
	lines.push(`        PixelShader = compile ps_4_0_level_9_1 ${shader.output.entryName}_PS();`);
	lines.push(`    }`);
	lines.push(`}`);

	return lines.join("\n");
}
